//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace Ais7IssoSServerCore
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatingHttps", Namespace="http://schemas.datacontract.org/2004/07/Ais7IssoSServerCore")]
    public partial class RatingHttps : object
    {
        
        private int CIssoField;
        
        private bool CheckOutField;
        
        private int CurrentRatingField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private long OffsetField;
        
        private long RatingDateField;
        
        private long RatingDateEditField;
        
        private string RatingExtField;
        
        private int RatingIssoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CIsso
        {
            get
            {
                return this.CIssoField;
            }
            set
            {
                this.CIssoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckOut
        {
            get
            {
                return this.CheckOutField;
            }
            set
            {
                this.CheckOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentRating
        {
            get
            {
                return this.CurrentRatingField;
            }
            set
            {
                this.CurrentRatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Offset
        {
            get
            {
                return this.OffsetField;
            }
            set
            {
                this.OffsetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RatingDate
        {
            get
            {
                return this.RatingDateField;
            }
            set
            {
                this.RatingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RatingDateEdit
        {
            get
            {
                return this.RatingDateEditField;
            }
            set
            {
                this.RatingDateEditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingExt
        {
            get
            {
                return this.RatingExtField;
            }
            set
            {
                this.RatingExtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RatingIsso
        {
            get
            {
                return this.RatingIssoField;
            }
            set
            {
                this.RatingIssoField = value;
            }
        }
    }
}
namespace ais7MobileCommonServerCore
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotoIssoS", Namespace="http://schemas.datacontract.org/2004/07/ais7MobileCommonServerCore")]
    public partial class PhotoIssoS : object
    {
        
        private int CIssoField;
        
        private string CommentField;
        
        private string PhotoField;
        
        private long PhotoDateField;
        
        private string PhotoPathField;
        
        private long RatingDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CIsso
        {
            get
            {
                return this.CIssoField;
            }
            set
            {
                this.CIssoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PhotoDate
        {
            get
            {
                return this.PhotoDateField;
            }
            set
            {
                this.PhotoDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath
        {
            get
            {
                return this.PhotoPathField;
            }
            set
            {
                this.PhotoPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RatingDate
        {
            get
            {
                return this.RatingDateField;
            }
            set
            {
                this.RatingDateField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="Iais7MobileIssoSServerCore")]
public interface Iais7MobileIssoSServerCore
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsGetSessionIdForIssoS", ReplyAction="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsGetSessionIdForIssoSResponse")]
    System.IAsyncResult BeginHttpsGetSessionIdForIssoS(string user, string pass, System.AsyncCallback callback, object asyncState);
    
    string[] EndHttpsGetSessionIdForIssoS(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsGetRatingInfo", ReplyAction="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsGetRatingInfoResponse")]
    System.IAsyncResult BeginHttpsGetRatingInfo(System.Guid id, int isso, System.AsyncCallback callback, object asyncState);
    
    Ais7IssoSServerCore.RatingHttps[] EndHttpsGetRatingInfo(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsSetRatingInfo", ReplyAction="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsSetRatingInfoResponse")]
    System.IAsyncResult BeginHttpsSetRatingInfo(System.Guid id, Ais7IssoSServerCore.RatingHttps[] ratings, System.AsyncCallback callback, object asyncState);
    
    int EndHttpsSetRatingInfo(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsSetPhotoIssoS", ReplyAction="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsSetPhotoIssoSResponse")]
    System.IAsyncResult BeginHttpsSetPhotoIssoS(System.Guid id, ais7MobileCommonServerCore.PhotoIssoS[] photos, System.AsyncCallback callback, object asyncState);
    
    int EndHttpsSetPhotoIssoS(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsReceiveInfoAboutPhotoForIssoS", ReplyAction="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsReceiveInfoAboutPhotoForIssoSR" +
        "esponse")]
    System.IAsyncResult BeginHttpsReceiveInfoAboutPhotoForIssoS(System.Guid id, int c_isso, ais7MobileCommonServerCore.PhotoIssoS[] photos, System.AsyncCallback callback, object asyncState);
    
    int EndHttpsReceiveInfoAboutPhotoForIssoS(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsGetPhotoIssoS", ReplyAction="http://tempuri.org/Iais7MobileIssoSServerCore/HttpsGetPhotoIssoSResponse")]
    System.IAsyncResult BeginHttpsGetPhotoIssoS(System.Guid id, int c_isso, System.AsyncCallback callback, object asyncState);
    
    ais7MobileCommonServerCore.PhotoIssoS[] EndHttpsGetPhotoIssoS(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface Iais7MobileIssoSServerCoreChannel : Iais7MobileIssoSServerCore, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsGetSessionIdForIssoSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsGetSessionIdForIssoSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsGetRatingInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsGetRatingInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Ais7IssoSServerCore.RatingHttps[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Ais7IssoSServerCore.RatingHttps[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsSetRatingInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsSetRatingInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public int Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsSetPhotoIssoSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsSetPhotoIssoSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public int Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsReceiveInfoAboutPhotoForIssoSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsReceiveInfoAboutPhotoForIssoSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public int Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsGetPhotoIssoSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsGetPhotoIssoSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public ais7MobileCommonServerCore.PhotoIssoS[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((ais7MobileCommonServerCore.PhotoIssoS[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Iais7MobileIssoSServerCoreClient : System.ServiceModel.ClientBase<Iais7MobileIssoSServerCore>, Iais7MobileIssoSServerCore
{
    
    private BeginOperationDelegate onBeginHttpsGetSessionIdForIssoSDelegate;
    
    private EndOperationDelegate onEndHttpsGetSessionIdForIssoSDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsGetSessionIdForIssoSCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsGetRatingInfoDelegate;
    
    private EndOperationDelegate onEndHttpsGetRatingInfoDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsGetRatingInfoCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsSetRatingInfoDelegate;
    
    private EndOperationDelegate onEndHttpsSetRatingInfoDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsSetRatingInfoCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsSetPhotoIssoSDelegate;
    
    private EndOperationDelegate onEndHttpsSetPhotoIssoSDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsSetPhotoIssoSCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsReceiveInfoAboutPhotoForIssoSDelegate;
    
    private EndOperationDelegate onEndHttpsReceiveInfoAboutPhotoForIssoSDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsReceiveInfoAboutPhotoForIssoSCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsGetPhotoIssoSDelegate;
    
    private EndOperationDelegate onEndHttpsGetPhotoIssoSDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsGetPhotoIssoSCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public Iais7MobileIssoSServerCoreClient()
    {
    }
    
    public Iais7MobileIssoSServerCoreClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Iais7MobileIssoSServerCoreClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Iais7MobileIssoSServerCoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Iais7MobileIssoSServerCoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<HttpsGetSessionIdForIssoSCompletedEventArgs> HttpsGetSessionIdForIssoSCompleted;
    
    public event System.EventHandler<HttpsGetRatingInfoCompletedEventArgs> HttpsGetRatingInfoCompleted;
    
    public event System.EventHandler<HttpsSetRatingInfoCompletedEventArgs> HttpsSetRatingInfoCompleted;
    
    public event System.EventHandler<HttpsSetPhotoIssoSCompletedEventArgs> HttpsSetPhotoIssoSCompleted;
    
    public event System.EventHandler<HttpsReceiveInfoAboutPhotoForIssoSCompletedEventArgs> HttpsReceiveInfoAboutPhotoForIssoSCompleted;
    
    public event System.EventHandler<HttpsGetPhotoIssoSCompletedEventArgs> HttpsGetPhotoIssoSCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult Iais7MobileIssoSServerCore.BeginHttpsGetSessionIdForIssoS(string user, string pass, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsGetSessionIdForIssoS(user, pass, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string[] Iais7MobileIssoSServerCore.EndHttpsGetSessionIdForIssoS(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsGetSessionIdForIssoS(result);
    }
    
    private System.IAsyncResult OnBeginHttpsGetSessionIdForIssoS(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string user = ((string)(inValues[0]));
        string pass = ((string)(inValues[1]));
        return ((Iais7MobileIssoSServerCore)(this)).BeginHttpsGetSessionIdForIssoS(user, pass, callback, asyncState);
    }
    
    private object[] OnEndHttpsGetSessionIdForIssoS(System.IAsyncResult result)
    {
        string[] retVal = ((Iais7MobileIssoSServerCore)(this)).EndHttpsGetSessionIdForIssoS(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsGetSessionIdForIssoSCompleted(object state)
    {
        if ((this.HttpsGetSessionIdForIssoSCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsGetSessionIdForIssoSCompleted(this, new HttpsGetSessionIdForIssoSCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsGetSessionIdForIssoSAsync(string user, string pass)
    {
        this.HttpsGetSessionIdForIssoSAsync(user, pass, null);
    }
    
    public void HttpsGetSessionIdForIssoSAsync(string user, string pass, object userState)
    {
        if ((this.onBeginHttpsGetSessionIdForIssoSDelegate == null))
        {
            this.onBeginHttpsGetSessionIdForIssoSDelegate = new BeginOperationDelegate(this.OnBeginHttpsGetSessionIdForIssoS);
        }
        if ((this.onEndHttpsGetSessionIdForIssoSDelegate == null))
        {
            this.onEndHttpsGetSessionIdForIssoSDelegate = new EndOperationDelegate(this.OnEndHttpsGetSessionIdForIssoS);
        }
        if ((this.onHttpsGetSessionIdForIssoSCompletedDelegate == null))
        {
            this.onHttpsGetSessionIdForIssoSCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsGetSessionIdForIssoSCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsGetSessionIdForIssoSDelegate, new object[] {
                    user,
                    pass}, this.onEndHttpsGetSessionIdForIssoSDelegate, this.onHttpsGetSessionIdForIssoSCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult Iais7MobileIssoSServerCore.BeginHttpsGetRatingInfo(System.Guid id, int isso, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsGetRatingInfo(id, isso, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Ais7IssoSServerCore.RatingHttps[] Iais7MobileIssoSServerCore.EndHttpsGetRatingInfo(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsGetRatingInfo(result);
    }
    
    private System.IAsyncResult OnBeginHttpsGetRatingInfo(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        int isso = ((int)(inValues[1]));
        return ((Iais7MobileIssoSServerCore)(this)).BeginHttpsGetRatingInfo(id, isso, callback, asyncState);
    }
    
    private object[] OnEndHttpsGetRatingInfo(System.IAsyncResult result)
    {
        Ais7IssoSServerCore.RatingHttps[] retVal = ((Iais7MobileIssoSServerCore)(this)).EndHttpsGetRatingInfo(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsGetRatingInfoCompleted(object state)
    {
        if ((this.HttpsGetRatingInfoCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsGetRatingInfoCompleted(this, new HttpsGetRatingInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsGetRatingInfoAsync(System.Guid id, int isso)
    {
        this.HttpsGetRatingInfoAsync(id, isso, null);
    }
    
    public void HttpsGetRatingInfoAsync(System.Guid id, int isso, object userState)
    {
        if ((this.onBeginHttpsGetRatingInfoDelegate == null))
        {
            this.onBeginHttpsGetRatingInfoDelegate = new BeginOperationDelegate(this.OnBeginHttpsGetRatingInfo);
        }
        if ((this.onEndHttpsGetRatingInfoDelegate == null))
        {
            this.onEndHttpsGetRatingInfoDelegate = new EndOperationDelegate(this.OnEndHttpsGetRatingInfo);
        }
        if ((this.onHttpsGetRatingInfoCompletedDelegate == null))
        {
            this.onHttpsGetRatingInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsGetRatingInfoCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsGetRatingInfoDelegate, new object[] {
                    id,
                    isso}, this.onEndHttpsGetRatingInfoDelegate, this.onHttpsGetRatingInfoCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult Iais7MobileIssoSServerCore.BeginHttpsSetRatingInfo(System.Guid id, Ais7IssoSServerCore.RatingHttps[] ratings, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsSetRatingInfo(id, ratings, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    int Iais7MobileIssoSServerCore.EndHttpsSetRatingInfo(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsSetRatingInfo(result);
    }
    
    private System.IAsyncResult OnBeginHttpsSetRatingInfo(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        Ais7IssoSServerCore.RatingHttps[] ratings = ((Ais7IssoSServerCore.RatingHttps[])(inValues[1]));
        return ((Iais7MobileIssoSServerCore)(this)).BeginHttpsSetRatingInfo(id, ratings, callback, asyncState);
    }
    
    private object[] OnEndHttpsSetRatingInfo(System.IAsyncResult result)
    {
        int retVal = ((Iais7MobileIssoSServerCore)(this)).EndHttpsSetRatingInfo(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsSetRatingInfoCompleted(object state)
    {
        if ((this.HttpsSetRatingInfoCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsSetRatingInfoCompleted(this, new HttpsSetRatingInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsSetRatingInfoAsync(System.Guid id, Ais7IssoSServerCore.RatingHttps[] ratings)
    {
        this.HttpsSetRatingInfoAsync(id, ratings, null);
    }
    
    public void HttpsSetRatingInfoAsync(System.Guid id, Ais7IssoSServerCore.RatingHttps[] ratings, object userState)
    {
        if ((this.onBeginHttpsSetRatingInfoDelegate == null))
        {
            this.onBeginHttpsSetRatingInfoDelegate = new BeginOperationDelegate(this.OnBeginHttpsSetRatingInfo);
        }
        if ((this.onEndHttpsSetRatingInfoDelegate == null))
        {
            this.onEndHttpsSetRatingInfoDelegate = new EndOperationDelegate(this.OnEndHttpsSetRatingInfo);
        }
        if ((this.onHttpsSetRatingInfoCompletedDelegate == null))
        {
            this.onHttpsSetRatingInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsSetRatingInfoCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsSetRatingInfoDelegate, new object[] {
                    id,
                    ratings}, this.onEndHttpsSetRatingInfoDelegate, this.onHttpsSetRatingInfoCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult Iais7MobileIssoSServerCore.BeginHttpsSetPhotoIssoS(System.Guid id, ais7MobileCommonServerCore.PhotoIssoS[] photos, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsSetPhotoIssoS(id, photos, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    int Iais7MobileIssoSServerCore.EndHttpsSetPhotoIssoS(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsSetPhotoIssoS(result);
    }
    
    private System.IAsyncResult OnBeginHttpsSetPhotoIssoS(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        ais7MobileCommonServerCore.PhotoIssoS[] photos = ((ais7MobileCommonServerCore.PhotoIssoS[])(inValues[1]));
        return ((Iais7MobileIssoSServerCore)(this)).BeginHttpsSetPhotoIssoS(id, photos, callback, asyncState);
    }
    
    private object[] OnEndHttpsSetPhotoIssoS(System.IAsyncResult result)
    {
        int retVal = ((Iais7MobileIssoSServerCore)(this)).EndHttpsSetPhotoIssoS(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsSetPhotoIssoSCompleted(object state)
    {
        if ((this.HttpsSetPhotoIssoSCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsSetPhotoIssoSCompleted(this, new HttpsSetPhotoIssoSCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsSetPhotoIssoSAsync(System.Guid id, ais7MobileCommonServerCore.PhotoIssoS[] photos)
    {
        this.HttpsSetPhotoIssoSAsync(id, photos, null);
    }
    
    public void HttpsSetPhotoIssoSAsync(System.Guid id, ais7MobileCommonServerCore.PhotoIssoS[] photos, object userState)
    {
        if ((this.onBeginHttpsSetPhotoIssoSDelegate == null))
        {
            this.onBeginHttpsSetPhotoIssoSDelegate = new BeginOperationDelegate(this.OnBeginHttpsSetPhotoIssoS);
        }
        if ((this.onEndHttpsSetPhotoIssoSDelegate == null))
        {
            this.onEndHttpsSetPhotoIssoSDelegate = new EndOperationDelegate(this.OnEndHttpsSetPhotoIssoS);
        }
        if ((this.onHttpsSetPhotoIssoSCompletedDelegate == null))
        {
            this.onHttpsSetPhotoIssoSCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsSetPhotoIssoSCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsSetPhotoIssoSDelegate, new object[] {
                    id,
                    photos}, this.onEndHttpsSetPhotoIssoSDelegate, this.onHttpsSetPhotoIssoSCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult Iais7MobileIssoSServerCore.BeginHttpsReceiveInfoAboutPhotoForIssoS(System.Guid id, int c_isso, ais7MobileCommonServerCore.PhotoIssoS[] photos, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsReceiveInfoAboutPhotoForIssoS(id, c_isso, photos, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    int Iais7MobileIssoSServerCore.EndHttpsReceiveInfoAboutPhotoForIssoS(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsReceiveInfoAboutPhotoForIssoS(result);
    }
    
    private System.IAsyncResult OnBeginHttpsReceiveInfoAboutPhotoForIssoS(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        int c_isso = ((int)(inValues[1]));
        ais7MobileCommonServerCore.PhotoIssoS[] photos = ((ais7MobileCommonServerCore.PhotoIssoS[])(inValues[2]));
        return ((Iais7MobileIssoSServerCore)(this)).BeginHttpsReceiveInfoAboutPhotoForIssoS(id, c_isso, photos, callback, asyncState);
    }
    
    private object[] OnEndHttpsReceiveInfoAboutPhotoForIssoS(System.IAsyncResult result)
    {
        int retVal = ((Iais7MobileIssoSServerCore)(this)).EndHttpsReceiveInfoAboutPhotoForIssoS(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsReceiveInfoAboutPhotoForIssoSCompleted(object state)
    {
        if ((this.HttpsReceiveInfoAboutPhotoForIssoSCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsReceiveInfoAboutPhotoForIssoSCompleted(this, new HttpsReceiveInfoAboutPhotoForIssoSCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsReceiveInfoAboutPhotoForIssoSAsync(System.Guid id, int c_isso, ais7MobileCommonServerCore.PhotoIssoS[] photos)
    {
        this.HttpsReceiveInfoAboutPhotoForIssoSAsync(id, c_isso, photos, null);
    }
    
    public void HttpsReceiveInfoAboutPhotoForIssoSAsync(System.Guid id, int c_isso, ais7MobileCommonServerCore.PhotoIssoS[] photos, object userState)
    {
        if ((this.onBeginHttpsReceiveInfoAboutPhotoForIssoSDelegate == null))
        {
            this.onBeginHttpsReceiveInfoAboutPhotoForIssoSDelegate = new BeginOperationDelegate(this.OnBeginHttpsReceiveInfoAboutPhotoForIssoS);
        }
        if ((this.onEndHttpsReceiveInfoAboutPhotoForIssoSDelegate == null))
        {
            this.onEndHttpsReceiveInfoAboutPhotoForIssoSDelegate = new EndOperationDelegate(this.OnEndHttpsReceiveInfoAboutPhotoForIssoS);
        }
        if ((this.onHttpsReceiveInfoAboutPhotoForIssoSCompletedDelegate == null))
        {
            this.onHttpsReceiveInfoAboutPhotoForIssoSCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsReceiveInfoAboutPhotoForIssoSCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsReceiveInfoAboutPhotoForIssoSDelegate, new object[] {
                    id,
                    c_isso,
                    photos}, this.onEndHttpsReceiveInfoAboutPhotoForIssoSDelegate, this.onHttpsReceiveInfoAboutPhotoForIssoSCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult Iais7MobileIssoSServerCore.BeginHttpsGetPhotoIssoS(System.Guid id, int c_isso, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsGetPhotoIssoS(id, c_isso, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ais7MobileCommonServerCore.PhotoIssoS[] Iais7MobileIssoSServerCore.EndHttpsGetPhotoIssoS(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsGetPhotoIssoS(result);
    }
    
    private System.IAsyncResult OnBeginHttpsGetPhotoIssoS(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        int c_isso = ((int)(inValues[1]));
        return ((Iais7MobileIssoSServerCore)(this)).BeginHttpsGetPhotoIssoS(id, c_isso, callback, asyncState);
    }
    
    private object[] OnEndHttpsGetPhotoIssoS(System.IAsyncResult result)
    {
        ais7MobileCommonServerCore.PhotoIssoS[] retVal = ((Iais7MobileIssoSServerCore)(this)).EndHttpsGetPhotoIssoS(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsGetPhotoIssoSCompleted(object state)
    {
        if ((this.HttpsGetPhotoIssoSCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsGetPhotoIssoSCompleted(this, new HttpsGetPhotoIssoSCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsGetPhotoIssoSAsync(System.Guid id, int c_isso)
    {
        this.HttpsGetPhotoIssoSAsync(id, c_isso, null);
    }
    
    public void HttpsGetPhotoIssoSAsync(System.Guid id, int c_isso, object userState)
    {
        if ((this.onBeginHttpsGetPhotoIssoSDelegate == null))
        {
            this.onBeginHttpsGetPhotoIssoSDelegate = new BeginOperationDelegate(this.OnBeginHttpsGetPhotoIssoS);
        }
        if ((this.onEndHttpsGetPhotoIssoSDelegate == null))
        {
            this.onEndHttpsGetPhotoIssoSDelegate = new EndOperationDelegate(this.OnEndHttpsGetPhotoIssoS);
        }
        if ((this.onHttpsGetPhotoIssoSCompletedDelegate == null))
        {
            this.onHttpsGetPhotoIssoSCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsGetPhotoIssoSCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsGetPhotoIssoSDelegate, new object[] {
                    id,
                    c_isso}, this.onEndHttpsGetPhotoIssoSDelegate, this.onHttpsGetPhotoIssoSCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override Iais7MobileIssoSServerCore CreateChannel()
    {
        return new Iais7MobileIssoSServerCoreClientChannel(this);
    }
    
    private class Iais7MobileIssoSServerCoreClientChannel : ChannelBase<Iais7MobileIssoSServerCore>, Iais7MobileIssoSServerCore
    {
        
        public Iais7MobileIssoSServerCoreClientChannel(System.ServiceModel.ClientBase<Iais7MobileIssoSServerCore> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginHttpsGetSessionIdForIssoS(string user, string pass, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = user;
            _args[1] = pass;
            System.IAsyncResult _result = base.BeginInvoke("HttpsGetSessionIdForIssoS", _args, callback, asyncState);
            return _result;
        }
        
        public string[] EndHttpsGetSessionIdForIssoS(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string[] _result = ((string[])(base.EndInvoke("HttpsGetSessionIdForIssoS", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsGetRatingInfo(System.Guid id, int isso, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = id;
            _args[1] = isso;
            System.IAsyncResult _result = base.BeginInvoke("HttpsGetRatingInfo", _args, callback, asyncState);
            return _result;
        }
        
        public Ais7IssoSServerCore.RatingHttps[] EndHttpsGetRatingInfo(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            Ais7IssoSServerCore.RatingHttps[] _result = ((Ais7IssoSServerCore.RatingHttps[])(base.EndInvoke("HttpsGetRatingInfo", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsSetRatingInfo(System.Guid id, Ais7IssoSServerCore.RatingHttps[] ratings, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = id;
            _args[1] = ratings;
            System.IAsyncResult _result = base.BeginInvoke("HttpsSetRatingInfo", _args, callback, asyncState);
            return _result;
        }
        
        public int EndHttpsSetRatingInfo(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            int _result = ((int)(base.EndInvoke("HttpsSetRatingInfo", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsSetPhotoIssoS(System.Guid id, ais7MobileCommonServerCore.PhotoIssoS[] photos, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = id;
            _args[1] = photos;
            System.IAsyncResult _result = base.BeginInvoke("HttpsSetPhotoIssoS", _args, callback, asyncState);
            return _result;
        }
        
        public int EndHttpsSetPhotoIssoS(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            int _result = ((int)(base.EndInvoke("HttpsSetPhotoIssoS", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsReceiveInfoAboutPhotoForIssoS(System.Guid id, int c_isso, ais7MobileCommonServerCore.PhotoIssoS[] photos, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = id;
            _args[1] = c_isso;
            _args[2] = photos;
            System.IAsyncResult _result = base.BeginInvoke("HttpsReceiveInfoAboutPhotoForIssoS", _args, callback, asyncState);
            return _result;
        }
        
        public int EndHttpsReceiveInfoAboutPhotoForIssoS(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            int _result = ((int)(base.EndInvoke("HttpsReceiveInfoAboutPhotoForIssoS", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsGetPhotoIssoS(System.Guid id, int c_isso, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = id;
            _args[1] = c_isso;
            System.IAsyncResult _result = base.BeginInvoke("HttpsGetPhotoIssoS", _args, callback, asyncState);
            return _result;
        }
        
        public ais7MobileCommonServerCore.PhotoIssoS[] EndHttpsGetPhotoIssoS(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            ais7MobileCommonServerCore.PhotoIssoS[] _result = ((ais7MobileCommonServerCore.PhotoIssoS[])(base.EndInvoke("HttpsGetPhotoIssoS", _args, result)));
            return _result;
        }
    }
}
