//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
using System;
using System.ServiceModel;
using Ais7IssoRServerCore;

namespace Ais7IssoRServerCore
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HttpsRemInfo", Namespace="http://schemas.datacontract.org/2004/07/Ais7IssoRServerCore")]
    public partial class HttpsRemInfo : object
    {
        
        private int CIssoField;
        
        private int CRemField;
        
        private int n1Field;
        
        private int n10Field;
        
        private int n11Field;
        
        private int n12Field;
        
        private int n2Field;
        
        private int n3Field;
        
        private int n4Field;
        
        private int n5Field;
        
        private int n6Field;
        
        private int n7Field;
        
        private int n8Field;
        
        private int n9Field;
        
        private string nRemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CIsso
        {
            get
            {
                return this.CIssoField;
            }
            set
            {
                this.CIssoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CRem
        {
            get
            {
                return this.CRemField;
            }
            set
            {
                this.CRemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n1
        {
            get
            {
                return this.n1Field;
            }
            set
            {
                this.n1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n10
        {
            get
            {
                return this.n10Field;
            }
            set
            {
                this.n10Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n11
        {
            get
            {
                return this.n11Field;
            }
            set
            {
                this.n11Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n12
        {
            get
            {
                return this.n12Field;
            }
            set
            {
                this.n12Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n2
        {
            get
            {
                return this.n2Field;
            }
            set
            {
                this.n2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n3
        {
            get
            {
                return this.n3Field;
            }
            set
            {
                this.n3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n4
        {
            get
            {
                return this.n4Field;
            }
            set
            {
                this.n4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n5
        {
            get
            {
                return this.n5Field;
            }
            set
            {
                this.n5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n6
        {
            get
            {
                return this.n6Field;
            }
            set
            {
                this.n6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n7
        {
            get
            {
                return this.n7Field;
            }
            set
            {
                this.n7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n8
        {
            get
            {
                return this.n8Field;
            }
            set
            {
                this.n8Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n9
        {
            get
            {
                return this.n9Field;
            }
            set
            {
                this.n9Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nRem
        {
            get
            {
                return this.nRemField;
            }
            set
            {
                this.nRemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemWork", Namespace="http://schemas.datacontract.org/2004/07/Ais7IssoRServerCore")]
    public partial class RemWork : object
    {
        
        private int CIssoField;
        
        private int CRemField;
        
        private string PhotoField;
        
        private string PhotoPathField;
        
        private int RatingRemField;
        
        private string RatingRemExtField;
        
        private long RemMonthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CIsso
        {
            get
            {
                return this.CIssoField;
            }
            set
            {
                this.CIssoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CRem
        {
            get
            {
                return this.CRemField;
            }
            set
            {
                this.CRemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath
        {
            get
            {
                return this.PhotoPathField;
            }
            set
            {
                this.PhotoPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RatingRem
        {
            get
            {
                return this.RatingRemField;
            }
            set
            {
                this.RatingRemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingRemExt
        {
            get
            {
                return this.RatingRemExtField;
            }
            set
            {
                this.RatingRemExtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RemMonth
        {
            get
            {
                return this.RemMonthField;
            }
            set
            {
                this.RemMonthField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HttpsRemCur", Namespace="http://schemas.datacontract.org/2004/07/Ais7IssoRServerCore")]
    public partial class HttpsRemCur : object
    {
        
        private int CIssoField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private string NPerformerField;
        
        private long OffsetField;
        
        private long RatingDateRemField;
        
        private long RatingDateRemEditField;
        
        private long RemMonthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CIsso
        {
            get
            {
                return this.CIssoField;
            }
            set
            {
                this.CIssoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NPerformer
        {
            get
            {
                return this.NPerformerField;
            }
            set
            {
                this.NPerformerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Offset
        {
            get
            {
                return this.OffsetField;
            }
            set
            {
                this.OffsetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RatingDateRem
        {
            get
            {
                return this.RatingDateRemField;
            }
            set
            {
                this.RatingDateRemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RatingDateRemEdit
        {
            get
            {
                return this.RatingDateRemEditField;
            }
            set
            {
                this.RatingDateRemEditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RemMonth
        {
            get
            {
                return this.RemMonthField;
            }
            set
            {
                this.RemMonthField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAis7MobileIssoRServerCoreXamarin")]
public interface IAis7MobileIssoRServerCoreXamarin
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsReceiveInfoAboutRemWork" +
        "s", ReplyAction="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsReceiveInfoAboutRemWork" +
        "sResponse")]
    System.IAsyncResult BeginHttpsReceiveInfoAboutRemWorks(System.Guid id, int isso, int[] ArrayCRem, System.AsyncCallback callback, object asyncState);
    
    int EndHttpsReceiveInfoAboutRemWorks(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsGetRemInfo", ReplyAction="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsGetRemInfoResponse")]
    System.IAsyncResult BeginHttpsGetRemInfo(System.Guid id, int isso, System.AsyncCallback callback, object asyncState);
    
    Ais7IssoRServerCore.HttpsRemInfo[] EndHttpsGetRemInfo(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsGetWorkRemRating", ReplyAction="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsGetWorkRemRatingRespons" +
        "e")]
    System.IAsyncResult BeginHttpsGetWorkRemRating(System.Guid id, int c_isso, bool download, System.AsyncCallback callback, object asyncState);
    
    Ais7IssoRServerCore.RemWork[] EndHttpsGetWorkRemRating(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsSendInfoAboutPhoto", ReplyAction="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsSendInfoAboutPhotoRespo" +
        "nse")]
    System.IAsyncResult BeginHttpsSendInfoAboutPhoto(System.Guid id, System.AsyncCallback callback, object asyncState);
    
    string[] EndHttpsSendInfoAboutPhoto(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsReceiveInfoAboutPhoto", ReplyAction="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsReceiveInfoAboutPhotoRe" +
        "sponse")]
    System.IAsyncResult BeginHttpsReceiveInfoAboutPhoto(System.Guid id, int c_isso, string[] photos, System.AsyncCallback callback, object asyncState);
    
    int EndHttpsReceiveInfoAboutPhoto(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsGetWorkRemCurator", ReplyAction="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsGetWorkRemCuratorRespon" +
        "se")]
    System.IAsyncResult BeginHttpsGetWorkRemCurator(System.Guid id, int c_isso, System.AsyncCallback callback, object asyncState);
    
    Ais7IssoRServerCore.HttpsRemCur[] EndHttpsGetWorkRemCurator(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsSetWorkRemRating", ReplyAction="http://tempuri.org/IAis7MobileIssoRServerCoreXamarin/HttpsSetWorkRemRatingRespons" +
        "e")]
    System.IAsyncResult BeginHttpsSetWorkRemRating(System.Guid id, Ais7IssoRServerCore.RemWork[] remWorks, Ais7IssoRServerCore.HttpsRemCur[] remCur, System.AsyncCallback callback, object asyncState);
    
    int EndHttpsSetWorkRemRating(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAis7MobileIssoRServerCoreXamarinChannel : IAis7MobileIssoRServerCoreXamarin, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsReceiveInfoAboutRemWorksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsReceiveInfoAboutRemWorksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public int Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsGetRemInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsGetRemInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Ais7IssoRServerCore.HttpsRemInfo[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Ais7IssoRServerCore.HttpsRemInfo[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsGetWorkRemRatingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsGetWorkRemRatingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Ais7IssoRServerCore.RemWork[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Ais7IssoRServerCore.RemWork[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsSendInfoAboutPhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsSendInfoAboutPhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsReceiveInfoAboutPhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsReceiveInfoAboutPhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public int Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsGetWorkRemCuratorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsGetWorkRemCuratorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Ais7IssoRServerCore.HttpsRemCur[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Ais7IssoRServerCore.HttpsRemCur[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HttpsSetWorkRemRatingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HttpsSetWorkRemRatingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public int Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

public class MyIssoRXamarinClient : ClientBase<IAis7MobileIssoRServerCoreXamarin>, IAis7MobileIssoRServerCoreXamarin
{
    // Timeout
    private int timeout = 30000;

    public MyIssoRXamarinClient() { }

    public MyIssoRXamarinClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsGetRemInfo(Guid id, int isso, AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsGetRemInfo(id, isso, callback, asyncState);
    }

    IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsGetWorkRemCurator(Guid id, int c_isso, AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsGetWorkRemCurator(id, c_isso, callback, asyncState);
    }

    IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsGetWorkRemRating(Guid id, int c_isso, bool download, AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsGetWorkRemRating(id, c_isso, download, callback, asyncState);
    }

    IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsReceiveInfoAboutPhoto(Guid id, int c_isso, string[] photos, AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsReceiveInfoAboutPhoto(id, c_isso, photos, callback, asyncState);
    }

    IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsReceiveInfoAboutRemWorks(Guid id, int isso, int[] ArrayCRem, AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsReceiveInfoAboutRemWorks(id, isso, ArrayCRem, callback, asyncState);
    }

    IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsSendInfoAboutPhoto(Guid id, AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsSendInfoAboutPhoto(id, callback, asyncState);
    }

    IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsSetWorkRemRating(Guid id, RemWork[] remWorks, HttpsRemCur[] remCur, AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsSetWorkRemRating(id, remWorks, remCur, callback, asyncState);
    }

    HttpsRemInfo[] IAis7MobileIssoRServerCoreXamarin.EndHttpsGetRemInfo(IAsyncResult result)
    {
        return base.Channel.EndHttpsGetRemInfo(result);
    }

    HttpsRemCur[] IAis7MobileIssoRServerCoreXamarin.EndHttpsGetWorkRemCurator(IAsyncResult result)
    {
        return base.Channel.EndHttpsGetWorkRemCurator(result);
    }

    RemWork[] IAis7MobileIssoRServerCoreXamarin.EndHttpsGetWorkRemRating(IAsyncResult result)
    {
        return base.Channel.EndHttpsGetWorkRemRating(result);
    }

    int IAis7MobileIssoRServerCoreXamarin.EndHttpsReceiveInfoAboutPhoto(IAsyncResult result)
    {
        return base.Channel.EndHttpsReceiveInfoAboutPhoto(result);
    }

    int IAis7MobileIssoRServerCoreXamarin.EndHttpsReceiveInfoAboutRemWorks(IAsyncResult result)
    {
        return base.Channel.EndHttpsReceiveInfoAboutRemWorks(result);
    }

    string[] IAis7MobileIssoRServerCoreXamarin.EndHttpsSendInfoAboutPhoto(IAsyncResult result)
    {
        return base.Channel.EndHttpsSendInfoAboutPhoto(result);
    }

    int IAis7MobileIssoRServerCoreXamarin.EndHttpsSetWorkRemRating(IAsyncResult result)
    {
        return base.Channel.EndHttpsSetWorkRemRating(result);
    }

    public int HttpsReceiveInfoAboutRemWorks(Guid id, int isso, int[] ArrayCRem)
    {
        var result = ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsReceiveInfoAboutRemWorks(id, isso, ArrayCRem, null, new object());
        if(result.AsyncWaitHandle.WaitOne(timeout))
        {
            return ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsReceiveInfoAboutRemWorks(result);
        }
        else { return -1; }
    }

    public HttpsRemInfo[] HttpsGetRemInfo(Guid id, int isso)
    {
        var result = ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsGetRemInfo(id, isso, null, new object());
        if(result.AsyncWaitHandle.WaitOne(timeout))
        {
            return ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsGetRemInfo(result);
        }
        else { return null; }
    }

    public RemWork[] HttpsGetWorkRemRating(Guid id, int c_isso, bool download)
    {
        var result = ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsGetWorkRemRating(id, c_isso, download, null, new object());
        if(result.AsyncWaitHandle.WaitOne(timeout))
        {
            return ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsGetWorkRemRating(result);
        }
        else { return null; }
    }

    public string[] HttpsSendInfoAboutPhoto(Guid id)
    {   
        var result = ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsSendInfoAboutPhoto(id, null, new object());
        if (result.AsyncWaitHandle.WaitOne(timeout))
        {
            return ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsSendInfoAboutPhoto(result);
        }
        else { return null; }
    }

    public int HttpsReceiveInfoAboutPhoto(Guid id, int c_isso, string[] photos)
    {
        var result = ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsReceiveInfoAboutPhoto(id, c_isso, photos, null, new object());
        if(result.AsyncWaitHandle.WaitOne(timeout))
        {
            return ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsReceiveInfoAboutPhoto(result);
        }
        else
        {
            return -1;
        }
    }

    public HttpsRemCur[] HttpsGetWorkRemCurator(Guid id, int c_isso)
    {
        var result = ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsGetWorkRemCurator(id, c_isso, null, new object());
        if(result.AsyncWaitHandle.WaitOne(timeout))
        {
            return ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsGetWorkRemCurator(result);
        }
        else
        {
            return null;
        }
    }

    public int HttpsSetWorkRemRating(Guid id, RemWork[] remWorks, HttpsRemCur[] remCur)
    {
        var result = ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsSetWorkRemRating(id, remWorks, remCur, null, new object());
        if(result.AsyncWaitHandle.WaitOne(timeout))
        {
            return ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsSetWorkRemRating(result);
        }
        else { return -1; }
    }
}


[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Ais7MobileIssoRServerCoreXamarinClient : System.ServiceModel.ClientBase<IAis7MobileIssoRServerCoreXamarin>, IAis7MobileIssoRServerCoreXamarin
{
    
    private BeginOperationDelegate onBeginHttpsReceiveInfoAboutRemWorksDelegate;
    
    private EndOperationDelegate onEndHttpsReceiveInfoAboutRemWorksDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsReceiveInfoAboutRemWorksCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsGetRemInfoDelegate;
    
    private EndOperationDelegate onEndHttpsGetRemInfoDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsGetRemInfoCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsGetWorkRemRatingDelegate;
    
    private EndOperationDelegate onEndHttpsGetWorkRemRatingDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsGetWorkRemRatingCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsSendInfoAboutPhotoDelegate;
    
    private EndOperationDelegate onEndHttpsSendInfoAboutPhotoDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsSendInfoAboutPhotoCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsReceiveInfoAboutPhotoDelegate;
    
    private EndOperationDelegate onEndHttpsReceiveInfoAboutPhotoDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsReceiveInfoAboutPhotoCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsGetWorkRemCuratorDelegate;
    
    private EndOperationDelegate onEndHttpsGetWorkRemCuratorDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsGetWorkRemCuratorCompletedDelegate;
    
    private BeginOperationDelegate onBeginHttpsSetWorkRemRatingDelegate;
    
    private EndOperationDelegate onEndHttpsSetWorkRemRatingDelegate;
    
    private System.Threading.SendOrPostCallback onHttpsSetWorkRemRatingCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public Ais7MobileIssoRServerCoreXamarinClient()
    {
    }
    
    public Ais7MobileIssoRServerCoreXamarinClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Ais7MobileIssoRServerCoreXamarinClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Ais7MobileIssoRServerCoreXamarinClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Ais7MobileIssoRServerCoreXamarinClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<HttpsReceiveInfoAboutRemWorksCompletedEventArgs> HttpsReceiveInfoAboutRemWorksCompleted;
    
    public event System.EventHandler<HttpsGetRemInfoCompletedEventArgs> HttpsGetRemInfoCompleted;
    
    public event System.EventHandler<HttpsGetWorkRemRatingCompletedEventArgs> HttpsGetWorkRemRatingCompleted;
    
    public event System.EventHandler<HttpsSendInfoAboutPhotoCompletedEventArgs> HttpsSendInfoAboutPhotoCompleted;
    
    public event System.EventHandler<HttpsReceiveInfoAboutPhotoCompletedEventArgs> HttpsReceiveInfoAboutPhotoCompleted;
    
    public event System.EventHandler<HttpsGetWorkRemCuratorCompletedEventArgs> HttpsGetWorkRemCuratorCompleted;
    
    public event System.EventHandler<HttpsSetWorkRemRatingCompletedEventArgs> HttpsSetWorkRemRatingCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsReceiveInfoAboutRemWorks(System.Guid id, int isso, int[] ArrayCRem, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsReceiveInfoAboutRemWorks(id, isso, ArrayCRem, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    int IAis7MobileIssoRServerCoreXamarin.EndHttpsReceiveInfoAboutRemWorks(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsReceiveInfoAboutRemWorks(result);
    }
    
    private System.IAsyncResult OnBeginHttpsReceiveInfoAboutRemWorks(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        int isso = ((int)(inValues[1]));
        int[] ArrayCRem = ((int[])(inValues[2]));
        return ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsReceiveInfoAboutRemWorks(id, isso, ArrayCRem, callback, asyncState);
    }
    
    private object[] OnEndHttpsReceiveInfoAboutRemWorks(System.IAsyncResult result)
    {
        int retVal = ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsReceiveInfoAboutRemWorks(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsReceiveInfoAboutRemWorksCompleted(object state)
    {
        if ((this.HttpsReceiveInfoAboutRemWorksCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsReceiveInfoAboutRemWorksCompleted(this, new HttpsReceiveInfoAboutRemWorksCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsReceiveInfoAboutRemWorksAsync(System.Guid id, int isso, int[] ArrayCRem)
    {
        this.HttpsReceiveInfoAboutRemWorksAsync(id, isso, ArrayCRem, null);
    }
    
    public void HttpsReceiveInfoAboutRemWorksAsync(System.Guid id, int isso, int[] ArrayCRem, object userState)
    {
        if ((this.onBeginHttpsReceiveInfoAboutRemWorksDelegate == null))
        {
            this.onBeginHttpsReceiveInfoAboutRemWorksDelegate = new BeginOperationDelegate(this.OnBeginHttpsReceiveInfoAboutRemWorks);
        }
        if ((this.onEndHttpsReceiveInfoAboutRemWorksDelegate == null))
        {
            this.onEndHttpsReceiveInfoAboutRemWorksDelegate = new EndOperationDelegate(this.OnEndHttpsReceiveInfoAboutRemWorks);
        }
        if ((this.onHttpsReceiveInfoAboutRemWorksCompletedDelegate == null))
        {
            this.onHttpsReceiveInfoAboutRemWorksCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsReceiveInfoAboutRemWorksCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsReceiveInfoAboutRemWorksDelegate, new object[] {
                    id,
                    isso,
                    ArrayCRem}, this.onEndHttpsReceiveInfoAboutRemWorksDelegate, this.onHttpsReceiveInfoAboutRemWorksCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsGetRemInfo(System.Guid id, int isso, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsGetRemInfo(id, isso, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Ais7IssoRServerCore.HttpsRemInfo[] IAis7MobileIssoRServerCoreXamarin.EndHttpsGetRemInfo(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsGetRemInfo(result);
    }
    
    private System.IAsyncResult OnBeginHttpsGetRemInfo(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        int isso = ((int)(inValues[1]));
        return ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsGetRemInfo(id, isso, callback, asyncState);
    }
    
    private object[] OnEndHttpsGetRemInfo(System.IAsyncResult result)
    {
        Ais7IssoRServerCore.HttpsRemInfo[] retVal = ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsGetRemInfo(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsGetRemInfoCompleted(object state)
    {
        if ((this.HttpsGetRemInfoCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsGetRemInfoCompleted(this, new HttpsGetRemInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsGetRemInfoAsync(System.Guid id, int isso)
    {
        this.HttpsGetRemInfoAsync(id, isso, null);
    }
    
    public void HttpsGetRemInfoAsync(System.Guid id, int isso, object userState)
    {
        if ((this.onBeginHttpsGetRemInfoDelegate == null))
        {
            this.onBeginHttpsGetRemInfoDelegate = new BeginOperationDelegate(this.OnBeginHttpsGetRemInfo);
        }
        if ((this.onEndHttpsGetRemInfoDelegate == null))
        {
            this.onEndHttpsGetRemInfoDelegate = new EndOperationDelegate(this.OnEndHttpsGetRemInfo);
        }
        if ((this.onHttpsGetRemInfoCompletedDelegate == null))
        {
            this.onHttpsGetRemInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsGetRemInfoCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsGetRemInfoDelegate, new object[] {
                    id,
                    isso}, this.onEndHttpsGetRemInfoDelegate, this.onHttpsGetRemInfoCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsGetWorkRemRating(System.Guid id, int c_isso, bool download, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsGetWorkRemRating(id, c_isso, download, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Ais7IssoRServerCore.RemWork[] IAis7MobileIssoRServerCoreXamarin.EndHttpsGetWorkRemRating(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsGetWorkRemRating(result);
    }
    
    private System.IAsyncResult OnBeginHttpsGetWorkRemRating(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        int c_isso = ((int)(inValues[1]));
        bool download = ((bool)(inValues[2]));
        return ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsGetWorkRemRating(id, c_isso, download, callback, asyncState);
    }
    
    private object[] OnEndHttpsGetWorkRemRating(System.IAsyncResult result)
    {
        Ais7IssoRServerCore.RemWork[] retVal = ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsGetWorkRemRating(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsGetWorkRemRatingCompleted(object state)
    {
        if ((this.HttpsGetWorkRemRatingCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsGetWorkRemRatingCompleted(this, new HttpsGetWorkRemRatingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsGetWorkRemRatingAsync(System.Guid id, int c_isso, bool download)
    {
        this.HttpsGetWorkRemRatingAsync(id, c_isso, download, null);
    }
    
    public void HttpsGetWorkRemRatingAsync(System.Guid id, int c_isso, bool download, object userState)
    {
        if ((this.onBeginHttpsGetWorkRemRatingDelegate == null))
        {
            this.onBeginHttpsGetWorkRemRatingDelegate = new BeginOperationDelegate(this.OnBeginHttpsGetWorkRemRating);
        }
        if ((this.onEndHttpsGetWorkRemRatingDelegate == null))
        {
            this.onEndHttpsGetWorkRemRatingDelegate = new EndOperationDelegate(this.OnEndHttpsGetWorkRemRating);
        }
        if ((this.onHttpsGetWorkRemRatingCompletedDelegate == null))
        {
            this.onHttpsGetWorkRemRatingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsGetWorkRemRatingCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsGetWorkRemRatingDelegate, new object[] {
                    id,
                    c_isso,
                    download}, this.onEndHttpsGetWorkRemRatingDelegate, this.onHttpsGetWorkRemRatingCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsSendInfoAboutPhoto(System.Guid id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsSendInfoAboutPhoto(id, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string[] IAis7MobileIssoRServerCoreXamarin.EndHttpsSendInfoAboutPhoto(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsSendInfoAboutPhoto(result);
    }
    
    private System.IAsyncResult OnBeginHttpsSendInfoAboutPhoto(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        return ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsSendInfoAboutPhoto(id, callback, asyncState);
    }
    
    private object[] OnEndHttpsSendInfoAboutPhoto(System.IAsyncResult result)
    {
        string[] retVal = ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsSendInfoAboutPhoto(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsSendInfoAboutPhotoCompleted(object state)
    {
        if ((this.HttpsSendInfoAboutPhotoCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsSendInfoAboutPhotoCompleted(this, new HttpsSendInfoAboutPhotoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsSendInfoAboutPhotoAsync(System.Guid id)
    {
        this.HttpsSendInfoAboutPhotoAsync(id, null);
    }
    
    public void HttpsSendInfoAboutPhotoAsync(System.Guid id, object userState)
    {
        if ((this.onBeginHttpsSendInfoAboutPhotoDelegate == null))
        {
            this.onBeginHttpsSendInfoAboutPhotoDelegate = new BeginOperationDelegate(this.OnBeginHttpsSendInfoAboutPhoto);
        }
        if ((this.onEndHttpsSendInfoAboutPhotoDelegate == null))
        {
            this.onEndHttpsSendInfoAboutPhotoDelegate = new EndOperationDelegate(this.OnEndHttpsSendInfoAboutPhoto);
        }
        if ((this.onHttpsSendInfoAboutPhotoCompletedDelegate == null))
        {
            this.onHttpsSendInfoAboutPhotoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsSendInfoAboutPhotoCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsSendInfoAboutPhotoDelegate, new object[] {
                    id}, this.onEndHttpsSendInfoAboutPhotoDelegate, this.onHttpsSendInfoAboutPhotoCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsReceiveInfoAboutPhoto(System.Guid id, int c_isso, string[] photos, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsReceiveInfoAboutPhoto(id, c_isso, photos, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    int IAis7MobileIssoRServerCoreXamarin.EndHttpsReceiveInfoAboutPhoto(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsReceiveInfoAboutPhoto(result);
    }
    
    private System.IAsyncResult OnBeginHttpsReceiveInfoAboutPhoto(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        int c_isso = ((int)(inValues[1]));
        string[] photos = ((string[])(inValues[2]));
        return ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsReceiveInfoAboutPhoto(id, c_isso, photos, callback, asyncState);
    }
    
    private object[] OnEndHttpsReceiveInfoAboutPhoto(System.IAsyncResult result)
    {
        int retVal = ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsReceiveInfoAboutPhoto(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsReceiveInfoAboutPhotoCompleted(object state)
    {
        if ((this.HttpsReceiveInfoAboutPhotoCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsReceiveInfoAboutPhotoCompleted(this, new HttpsReceiveInfoAboutPhotoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsReceiveInfoAboutPhotoAsync(System.Guid id, int c_isso, string[] photos)
    {
        this.HttpsReceiveInfoAboutPhotoAsync(id, c_isso, photos, null);
    }
    
    public void HttpsReceiveInfoAboutPhotoAsync(System.Guid id, int c_isso, string[] photos, object userState)
    {
        if ((this.onBeginHttpsReceiveInfoAboutPhotoDelegate == null))
        {
            this.onBeginHttpsReceiveInfoAboutPhotoDelegate = new BeginOperationDelegate(this.OnBeginHttpsReceiveInfoAboutPhoto);
        }
        if ((this.onEndHttpsReceiveInfoAboutPhotoDelegate == null))
        {
            this.onEndHttpsReceiveInfoAboutPhotoDelegate = new EndOperationDelegate(this.OnEndHttpsReceiveInfoAboutPhoto);
        }
        if ((this.onHttpsReceiveInfoAboutPhotoCompletedDelegate == null))
        {
            this.onHttpsReceiveInfoAboutPhotoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsReceiveInfoAboutPhotoCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsReceiveInfoAboutPhotoDelegate, new object[] {
                    id,
                    c_isso,
                    photos}, this.onEndHttpsReceiveInfoAboutPhotoDelegate, this.onHttpsReceiveInfoAboutPhotoCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsGetWorkRemCurator(System.Guid id, int c_isso, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsGetWorkRemCurator(id, c_isso, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Ais7IssoRServerCore.HttpsRemCur[] IAis7MobileIssoRServerCoreXamarin.EndHttpsGetWorkRemCurator(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsGetWorkRemCurator(result);
    }
    
    private System.IAsyncResult OnBeginHttpsGetWorkRemCurator(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        int c_isso = ((int)(inValues[1]));
        return ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsGetWorkRemCurator(id, c_isso, callback, asyncState);
    }
    
    private object[] OnEndHttpsGetWorkRemCurator(System.IAsyncResult result)
    {
        Ais7IssoRServerCore.HttpsRemCur[] retVal = ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsGetWorkRemCurator(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsGetWorkRemCuratorCompleted(object state)
    {
        if ((this.HttpsGetWorkRemCuratorCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsGetWorkRemCuratorCompleted(this, new HttpsGetWorkRemCuratorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsGetWorkRemCuratorAsync(System.Guid id, int c_isso)
    {
        this.HttpsGetWorkRemCuratorAsync(id, c_isso, null);
    }
    
    public void HttpsGetWorkRemCuratorAsync(System.Guid id, int c_isso, object userState)
    {
        if ((this.onBeginHttpsGetWorkRemCuratorDelegate == null))
        {
            this.onBeginHttpsGetWorkRemCuratorDelegate = new BeginOperationDelegate(this.OnBeginHttpsGetWorkRemCurator);
        }
        if ((this.onEndHttpsGetWorkRemCuratorDelegate == null))
        {
            this.onEndHttpsGetWorkRemCuratorDelegate = new EndOperationDelegate(this.OnEndHttpsGetWorkRemCurator);
        }
        if ((this.onHttpsGetWorkRemCuratorCompletedDelegate == null))
        {
            this.onHttpsGetWorkRemCuratorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsGetWorkRemCuratorCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsGetWorkRemCuratorDelegate, new object[] {
                    id,
                    c_isso}, this.onEndHttpsGetWorkRemCuratorDelegate, this.onHttpsGetWorkRemCuratorCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAis7MobileIssoRServerCoreXamarin.BeginHttpsSetWorkRemRating(System.Guid id, Ais7IssoRServerCore.RemWork[] remWorks, Ais7IssoRServerCore.HttpsRemCur[] remCur, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHttpsSetWorkRemRating(id, remWorks, remCur, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    int IAis7MobileIssoRServerCoreXamarin.EndHttpsSetWorkRemRating(System.IAsyncResult result)
    {
        return base.Channel.EndHttpsSetWorkRemRating(result);
    }
    
    private System.IAsyncResult OnBeginHttpsSetWorkRemRating(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid id = ((System.Guid)(inValues[0]));
        Ais7IssoRServerCore.RemWork[] remWorks = ((Ais7IssoRServerCore.RemWork[])(inValues[1]));
        Ais7IssoRServerCore.HttpsRemCur[] remCur = ((Ais7IssoRServerCore.HttpsRemCur[])(inValues[2]));
        return ((IAis7MobileIssoRServerCoreXamarin)(this)).BeginHttpsSetWorkRemRating(id, remWorks, remCur, callback, asyncState);
    }
    
    private object[] OnEndHttpsSetWorkRemRating(System.IAsyncResult result)
    {
        int retVal = ((IAis7MobileIssoRServerCoreXamarin)(this)).EndHttpsSetWorkRemRating(result);
        return new object[] {
                retVal};
    }
    
    private void OnHttpsSetWorkRemRatingCompleted(object state)
    {
        if ((this.HttpsSetWorkRemRatingCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HttpsSetWorkRemRatingCompleted(this, new HttpsSetWorkRemRatingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HttpsSetWorkRemRatingAsync(System.Guid id, Ais7IssoRServerCore.RemWork[] remWorks, Ais7IssoRServerCore.HttpsRemCur[] remCur)
    {
        this.HttpsSetWorkRemRatingAsync(id, remWorks, remCur, null);
    }
    
    public void HttpsSetWorkRemRatingAsync(System.Guid id, Ais7IssoRServerCore.RemWork[] remWorks, Ais7IssoRServerCore.HttpsRemCur[] remCur, object userState)
    {
        if ((this.onBeginHttpsSetWorkRemRatingDelegate == null))
        {
            this.onBeginHttpsSetWorkRemRatingDelegate = new BeginOperationDelegate(this.OnBeginHttpsSetWorkRemRating);
        }
        if ((this.onEndHttpsSetWorkRemRatingDelegate == null))
        {
            this.onEndHttpsSetWorkRemRatingDelegate = new EndOperationDelegate(this.OnEndHttpsSetWorkRemRating);
        }
        if ((this.onHttpsSetWorkRemRatingCompletedDelegate == null))
        {
            this.onHttpsSetWorkRemRatingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHttpsSetWorkRemRatingCompleted);
        }
        base.InvokeAsync(this.onBeginHttpsSetWorkRemRatingDelegate, new object[] {
                    id,
                    remWorks,
                    remCur}, this.onEndHttpsSetWorkRemRatingDelegate, this.onHttpsSetWorkRemRatingCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IAis7MobileIssoRServerCoreXamarin CreateChannel()
    {
        return new Ais7MobileIssoRServerCoreXamarinClientChannel(this);
    }
    
    private class Ais7MobileIssoRServerCoreXamarinClientChannel : ChannelBase<IAis7MobileIssoRServerCoreXamarin>, IAis7MobileIssoRServerCoreXamarin
    {
        
        public Ais7MobileIssoRServerCoreXamarinClientChannel(System.ServiceModel.ClientBase<IAis7MobileIssoRServerCoreXamarin> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginHttpsReceiveInfoAboutRemWorks(System.Guid id, int isso, int[] ArrayCRem, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = id;
            _args[1] = isso;
            _args[2] = ArrayCRem;
            System.IAsyncResult _result = base.BeginInvoke("HttpsReceiveInfoAboutRemWorks", _args, callback, asyncState);
            return _result;
        }
        
        public int EndHttpsReceiveInfoAboutRemWorks(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            int _result = ((int)(base.EndInvoke("HttpsReceiveInfoAboutRemWorks", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsGetRemInfo(System.Guid id, int isso, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = id;
            _args[1] = isso;
            System.IAsyncResult _result = base.BeginInvoke("HttpsGetRemInfo", _args, callback, asyncState);
            return _result;
        }
        
        public Ais7IssoRServerCore.HttpsRemInfo[] EndHttpsGetRemInfo(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            Ais7IssoRServerCore.HttpsRemInfo[] _result = ((Ais7IssoRServerCore.HttpsRemInfo[])(base.EndInvoke("HttpsGetRemInfo", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsGetWorkRemRating(System.Guid id, int c_isso, bool download, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = id;
            _args[1] = c_isso;
            _args[2] = download;
            System.IAsyncResult _result = base.BeginInvoke("HttpsGetWorkRemRating", _args, callback, asyncState);
            return _result;
        }
        
        public Ais7IssoRServerCore.RemWork[] EndHttpsGetWorkRemRating(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            Ais7IssoRServerCore.RemWork[] _result = ((Ais7IssoRServerCore.RemWork[])(base.EndInvoke("HttpsGetWorkRemRating", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsSendInfoAboutPhoto(System.Guid id, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = id;
            System.IAsyncResult _result = base.BeginInvoke("HttpsSendInfoAboutPhoto", _args, callback, asyncState);
            return _result;
        }
        
        public string[] EndHttpsSendInfoAboutPhoto(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string[] _result = ((string[])(base.EndInvoke("HttpsSendInfoAboutPhoto", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsReceiveInfoAboutPhoto(System.Guid id, int c_isso, string[] photos, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = id;
            _args[1] = c_isso;
            _args[2] = photos;
            System.IAsyncResult _result = base.BeginInvoke("HttpsReceiveInfoAboutPhoto", _args, callback, asyncState);
            return _result;
        }
        
        public int EndHttpsReceiveInfoAboutPhoto(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            int _result = ((int)(base.EndInvoke("HttpsReceiveInfoAboutPhoto", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsGetWorkRemCurator(System.Guid id, int c_isso, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = id;
            _args[1] = c_isso;
            System.IAsyncResult _result = base.BeginInvoke("HttpsGetWorkRemCurator", _args, callback, asyncState);
            return _result;
        }
        
        public Ais7IssoRServerCore.HttpsRemCur[] EndHttpsGetWorkRemCurator(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            Ais7IssoRServerCore.HttpsRemCur[] _result = ((Ais7IssoRServerCore.HttpsRemCur[])(base.EndInvoke("HttpsGetWorkRemCurator", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHttpsSetWorkRemRating(System.Guid id, Ais7IssoRServerCore.RemWork[] remWorks, Ais7IssoRServerCore.HttpsRemCur[] remCur, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = id;
            _args[1] = remWorks;
            _args[2] = remCur;
            System.IAsyncResult _result = base.BeginInvoke("HttpsSetWorkRemRating", _args, callback, asyncState);
            return _result;
        }
        
        public int EndHttpsSetWorkRemRating(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            int _result = ((int)(base.EndInvoke("HttpsSetWorkRemRating", _args, result)));
            return _result;
        }
    }
}
